Mhd/basemap styles
Esri/arcgis-runtime-toolkit-ios pull request #130
Opened 2021-01-20 17:55 UTC by mhdostal

Use the new base map style constructors when creating maps.  Add APIKey placeholder code.  A link will be added to the api key comments in AppDelegate once the Citra doc is live.

2021-01-20 19:26 UTC, zkline101 requested changes

2021-01-20 19:26 UTC, zkline101 commented on Examples/ArcGISToolkitExamples/AppDelegate.swift
> +        // AGSArcGISRuntimeEnvironment.apiKey = “<#API Key#>”
Looks like with the copy and paste of this doc different quotes were added. If you uncomment this line you will get an error saying, 
> Unicode curly quote found, replace with '"'

This should fix it when you delete those quotes and add new ones manually.

```suggestion
        // AGSArcGISRuntimeEnvironment.apiKey = "<#API Key#>"
```

2021-01-20 19:46 UTC, zkline101 approved these changes

2021-01-21 17:02 UTC, njarecha approved these changes

2021-01-21 17:02 UTC, merged